#!/bin/bash
# ============================================================================
#  Product Entry - Installation Script
#  Designed for Ubuntu Server 24.04 LTS (Minimal Install)
#
#  Usage:  curl -fsSL <raw-url>/install.sh | sudo bash
#     or:  sudo bash install.sh
#
#  Options:
#    1) Install    - Fresh production install
#    2) Update     - Pull latest from GitHub, preserve data, rebuild
#    3) Remove     - Stop and remove containers, optionally remove data
# ============================================================================

set -e

# ── Config ──────────────────────────────────────────────
APP_NAME="product-entry"
INSTALL_DIR="/opt/${APP_NAME}"
REPO_URL="https://github.com/ruolez/product-entry.git"
COMPOSE_PROJECT="product-entry"
DOCKER_COMPOSE="docker compose"
PORT=80

# ── Colors ──────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ── Helpers ─────────────────────────────────────────────
print_header() {
    echo ""
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BOLD}  $1${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

print_step() {
    echo -e "${CYAN}  ▸ $1${NC}"
}

print_ok() {
    echo -e "${GREEN}  ✓ $1${NC}"
}

print_warn() {
    echo -e "${YELLOW}  ⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}  ✗ $1${NC}"
}

# ── Root Check ──────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
    print_error "This script must be run as root (sudo)"
    exit 1
fi

# ── Detect IP ───────────────────────────────────────────
detect_ip() {
    # Try to get the primary non-loopback IPv4 address
    local ip=""

    # Method 1: ip route
    ip=$(ip -4 route get 8.8.8.8 2>/dev/null | grep -oP 'src \K[\d.]+' | head -1)

    # Method 2: hostname -I
    if [ -z "$ip" ]; then
        ip=$(hostname -I 2>/dev/null | awk '{print $1}')
    fi

    # Method 3: ip addr
    if [ -z "$ip" ]; then
        ip=$(ip -4 addr show scope global | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -1)
    fi

    echo "$ip"
}

# ── Generate Secrets ────────────────────────────────────
generate_password() {
    openssl rand -base64 24 | tr -d '/+=' | head -c 24
}

generate_fernet_key() {
    python3 -c "import base64, os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())" 2>/dev/null \
        || openssl rand -base64 32 | head -c 44
}

# ── Install Docker ──────────────────────────────────────
install_docker() {
    if command -v docker &>/dev/null; then
        print_ok "Docker already installed: $(docker --version | head -1)"
        return
    fi

    print_step "Installing Docker..."
    apt-get update -qq
    apt-get install -y -qq ca-certificates curl gnupg lsb-release >/dev/null 2>&1

    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc

    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
      https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      tee /etc/apt/sources.list.d/docker.list >/dev/null

    apt-get update -qq
    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin >/dev/null 2>&1

    systemctl enable docker --now
    print_ok "Docker installed: $(docker --version | head -1)"
}

# ── Install Dependencies ────────────────────────────────
install_dependencies() {
    print_step "Installing system dependencies..."
    apt-get update -qq
    apt-get install -y -qq git curl openssl python3 >/dev/null 2>&1
    print_ok "System dependencies installed"
}

# ── Generate Production Configs ─────────────────────────
generate_env_file() {
    local server_ip="$1"
    local pg_pass="$2"
    local fernet_key="$3"

    cat > "${INSTALL_DIR}/.env" << ENVEOF
# Production environment - Generated by install.sh
POSTGRES_USER=itementry
POSTGRES_PASSWORD=${pg_pass}
POSTGRES_DB=itementry
DATABASE_URL=postgresql://itementry:${pg_pass}@postgres:5432/itementry
FERNET_KEY=${fernet_key}
FLASK_ENV=production
SERVER_IP=${server_ip}
ENVEOF

    chmod 600 "${INSTALL_DIR}/.env"
    print_ok ".env generated with secure credentials"
}

generate_prod_compose() {
    local server_ip="$1"

    cat > "${INSTALL_DIR}/docker-compose.prod.yml" << 'COMPEOF'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - product-entry-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - product-entry-net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - product-entry-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  product-entry-net:
    driver: bridge

volumes:
  pgdata:
COMPEOF

    print_ok "docker-compose.prod.yml generated"
}

generate_prod_dockerfile() {
    cat > "${INSTALL_DIR}/app/Dockerfile.prod" << 'DKEOF'
FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    freetds-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Production: no --reload, more workers, preload for faster startups
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "4", "--preload", "--access-logfile", "-", "--error-logfile", "-", "wsgi:app"]
DKEOF

    print_ok "Dockerfile.prod generated (4 workers, no auto-reload)"
}

generate_prod_nginx() {
    local server_ip="$1"

    cat > "${INSTALL_DIR}/nginx/nginx.conf" << NGEOF
server {
    listen 80;
    server_name ${server_ip} localhost;

    # Disable caching for instant updates
    add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
    add_header Pragma "no-cache" always;

    # CORS headers for API access from server IP
    add_header Access-Control-Allow-Origin "http://${server_ip}" always;
    add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
    add_header Access-Control-Allow-Headers "Content-Type, Authorization, Cache-Control, Pragma" always;

    # Security headers
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Handle preflight CORS requests
    location @cors_preflight {
        add_header Access-Control-Allow-Origin "http://${server_ip}" always;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Content-Type, Authorization, Cache-Control, Pragma" always;
        add_header Access-Control-Max-Age 86400;
        add_header Content-Length 0;
        add_header Content-Type text/plain;
        return 204;
    }

    location / {
        if (\$request_method = OPTIONS) {
            return 204;
        }
        proxy_pass http://app:5000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # Timeouts for slow MS SQL connections
        proxy_connect_timeout 30s;
        proxy_read_timeout 120s;
        proxy_send_timeout 30s;
    }

    location /static/ {
        proxy_pass http://app:5000/static/;
        expires -1;
    }

    # Block common exploit paths
    location ~* \.(php|asp|aspx|jsp)$ {
        return 444;
    }
}
NGEOF

    print_ok "nginx.conf generated for ${server_ip}"
}

# ════════════════════════════════════════════════════════
#  INSTALL
# ════════════════════════════════════════════════════════
do_install() {
    print_header "FRESH INSTALL - Product Entry"

    # Check if already installed
    if [ -d "$INSTALL_DIR" ]; then
        print_warn "Installation found at ${INSTALL_DIR}"
        read -rp "  Remove existing installation and start fresh? (y/N): " confirm
        if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
            print_warn "Install cancelled."
            return
        fi
        do_remove_silent
    fi

    # Detect IP
    local server_ip
    server_ip=$(detect_ip)
    if [ -z "$server_ip" ]; then
        read -rp "  Could not detect IP. Enter server IP address: " server_ip
    else
        echo ""
        echo -e "  Detected IP: ${BOLD}${server_ip}${NC}"
        read -rp "  Use this IP? (Y/n): " use_ip
        if [[ "$use_ip" == "n" || "$use_ip" == "N" ]]; then
            read -rp "  Enter server IP address: " server_ip
        fi
    fi

    if [ -z "$server_ip" ]; then
        print_error "IP address is required."
        exit 1
    fi

    echo ""
    install_dependencies
    install_docker

    # Clone repository
    print_step "Cloning repository..."
    git clone --depth 1 "$REPO_URL" "$INSTALL_DIR" >/dev/null 2>&1
    print_ok "Repository cloned to ${INSTALL_DIR}"

    # Generate secrets
    local pg_pass
    local fernet_key
    pg_pass=$(generate_password)
    fernet_key=$(generate_fernet_key)

    # Generate production configs
    print_step "Generating production configuration..."
    generate_env_file "$server_ip" "$pg_pass" "$fernet_key"
    generate_prod_compose "$server_ip"
    generate_prod_dockerfile
    generate_prod_nginx "$server_ip"

    # Build and start
    print_step "Building Docker containers (this may take a few minutes)..."
    cd "$INSTALL_DIR"
    $DOCKER_COMPOSE -f docker-compose.prod.yml -p "$COMPOSE_PROJECT" build --quiet 2>&1
    print_ok "Containers built"

    print_step "Starting services..."
    $DOCKER_COMPOSE -f docker-compose.prod.yml -p "$COMPOSE_PROJECT" up -d 2>&1
    print_ok "Services started"

    # Wait for health check
    print_step "Waiting for services to be ready..."
    local retries=0
    while [ $retries -lt 30 ]; do
        if curl -sf "http://localhost:${PORT}/api/health" >/dev/null 2>&1; then
            break
        fi
        sleep 2
        retries=$((retries + 1))
    done

    if curl -sf "http://localhost:${PORT}/api/health" >/dev/null 2>&1; then
        print_ok "All services healthy"
    else
        print_warn "Services may still be starting. Check logs with:"
        echo "    cd ${INSTALL_DIR} && docker compose -f docker-compose.prod.yml -p ${COMPOSE_PROJECT} logs"
    fi

    # Print summary
    print_header "INSTALLATION COMPLETE"
    echo ""
    echo -e "  ${GREEN}Product Entry is running!${NC}"
    echo ""
    echo -e "  ${BOLD}Access:${NC}        http://${server_ip}"
    echo -e "  ${BOLD}Settings:${NC}      http://${server_ip}/settings"
    echo -e "  ${BOLD}Install Dir:${NC}   ${INSTALL_DIR}"
    echo ""
    echo -e "  ${BOLD}Quick Start:${NC}"
    echo -e "    1. Go to ${CYAN}http://${server_ip}/settings${NC}"
    echo -e "    2. Add your MS SQL store connections"
    echo -e "    3. Configure price formulas"
    echo -e "    4. Start entering products at ${CYAN}http://${server_ip}${NC}"
    echo ""
    echo -e "  ${BOLD}Commands:${NC}"
    echo -e "    View logs:      cd ${INSTALL_DIR} && docker compose -f docker-compose.prod.yml -p ${COMPOSE_PROJECT} logs -f"
    echo -e "    Restart:        cd ${INSTALL_DIR} && docker compose -f docker-compose.prod.yml -p ${COMPOSE_PROJECT} restart"
    echo -e "    Update:         sudo bash ${INSTALL_DIR}/install.sh"
    echo ""
}

# ════════════════════════════════════════════════════════
#  UPDATE
# ════════════════════════════════════════════════════════
do_update() {
    print_header "UPDATE - Product Entry"

    if [ ! -d "$INSTALL_DIR" ]; then
        print_error "No installation found at ${INSTALL_DIR}. Run Install first."
        return
    fi

    cd "$INSTALL_DIR"

    # Read current IP from .env
    local current_ip=""
    if [ -f ".env" ]; then
        current_ip=$(grep '^SERVER_IP=' .env | cut -d'=' -f2)
    fi

    local server_ip
    server_ip=$(detect_ip)
    if [ -n "$current_ip" ]; then
        echo -e "  Current IP: ${BOLD}${current_ip}${NC}"
        echo -e "  Detected IP: ${BOLD}${server_ip}${NC}"
        read -rp "  Use detected IP? (Y/n/custom): " use_ip
        if [[ "$use_ip" == "n" || "$use_ip" == "N" ]]; then
            server_ip="$current_ip"
        elif [[ "$use_ip" != "" && "$use_ip" != "y" && "$use_ip" != "Y" ]]; then
            server_ip="$use_ip"
        fi
    fi

    # Backup current .env (preserve secrets)
    print_step "Preserving configuration and data..."
    local pg_pass fernet_key
    pg_pass=$(grep '^POSTGRES_PASSWORD=' .env | cut -d'=' -f2)
    fernet_key=$(grep '^FERNET_KEY=' .env | cut -d'=' -f2)
    cp .env .env.backup
    print_ok "Configuration backed up"

    # Stop containers (data is in Docker volume, safe)
    print_step "Stopping services..."
    $DOCKER_COMPOSE -f docker-compose.prod.yml -p "$COMPOSE_PROJECT" down 2>/dev/null || \
    $DOCKER_COMPOSE -p "$COMPOSE_PROJECT" down 2>/dev/null || true
    print_ok "Services stopped"

    # Pull latest from GitHub
    print_step "Pulling latest code from GitHub..."
    git fetch origin main 2>&1
    git reset --hard origin/main 2>&1
    print_ok "Code updated to latest"

    # Re-copy install.sh to ensure it's the latest
    # (the user may be running the old version of this script)

    # Regenerate production configs (preserving secrets)
    print_step "Regenerating production configuration..."
    generate_env_file "$server_ip" "$pg_pass" "$fernet_key"
    generate_prod_compose "$server_ip"
    generate_prod_dockerfile
    generate_prod_nginx "$server_ip"

    # Rebuild containers
    print_step "Rebuilding containers..."
    $DOCKER_COMPOSE -f docker-compose.prod.yml -p "$COMPOSE_PROJECT" build --no-cache --quiet 2>&1
    print_ok "Containers rebuilt"

    # Start services
    print_step "Starting services..."
    $DOCKER_COMPOSE -f docker-compose.prod.yml -p "$COMPOSE_PROJECT" up -d 2>&1
    print_ok "Services started"

    # Cleanup old Docker resources
    print_step "Cleaning up old Docker images and build cache..."
    docker image prune -f >/dev/null 2>&1
    docker builder prune -f >/dev/null 2>&1
    print_ok "Unused images and cache cleaned"

    # Truncate old container logs
    print_step "Cleaning up old container logs..."
    find /var/lib/docker/containers/ -name "*.log" -size +10M -exec truncate -s 0 {} \; 2>/dev/null || true
    print_ok "Large log files truncated"

    # Wait for health
    print_step "Waiting for services to be ready..."
    local retries=0
    while [ $retries -lt 30 ]; do
        if curl -sf "http://localhost:${PORT}/api/health" >/dev/null 2>&1; then
            break
        fi
        sleep 2
        retries=$((retries + 1))
    done

    if curl -sf "http://localhost:${PORT}/api/health" >/dev/null 2>&1; then
        print_ok "All services healthy"
    else
        print_warn "Services may still be starting. Check logs."
    fi

    # Verify data preserved
    local store_count
    store_count=$($DOCKER_COMPOSE -f docker-compose.prod.yml -p "$COMPOSE_PROJECT" exec -T postgres \
        psql -U itementry -d itementry -t -c "SELECT count(*) FROM stores;" 2>/dev/null | tr -d ' ' || echo "?")
    local formula_count
    formula_count=$($DOCKER_COMPOSE -f docker-compose.prod.yml -p "$COMPOSE_PROJECT" exec -T postgres \
        psql -U itementry -d itementry -t -c "SELECT count(*) FROM price_formulas;" 2>/dev/null | tr -d ' ' || echo "?")

    print_header "UPDATE COMPLETE"
    echo ""
    echo -e "  ${GREEN}Product Entry updated successfully!${NC}"
    echo ""
    echo -e "  ${BOLD}Access:${NC}          http://${server_ip}"
    echo -e "  ${BOLD}Data preserved:${NC}  ${store_count} stores, ${formula_count} price formulas"
    echo -e "  ${BOLD}Backup:${NC}          ${INSTALL_DIR}/.env.backup"
    echo ""
}

# ════════════════════════════════════════════════════════
#  REMOVE
# ════════════════════════════════════════════════════════
do_remove() {
    print_header "REMOVE - Product Entry"

    if [ ! -d "$INSTALL_DIR" ]; then
        print_warn "No installation found at ${INSTALL_DIR}"
        return
    fi

    echo ""
    echo -e "  ${YELLOW}This will stop all Product Entry services.${NC}"
    echo ""
    read -rp "  Remove application? (y/N): " confirm
    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
        print_warn "Remove cancelled."
        return
    fi

    cd "$INSTALL_DIR"

    # Stop and remove containers
    print_step "Stopping and removing containers..."
    $DOCKER_COMPOSE -f docker-compose.prod.yml -p "$COMPOSE_PROJECT" down 2>/dev/null || \
    $DOCKER_COMPOSE -p "$COMPOSE_PROJECT" down 2>/dev/null || true
    print_ok "Containers stopped and removed"

    # Ask about data
    echo ""
    echo -e "  ${YELLOW}Do you want to remove the database data?${NC}"
    echo -e "  ${YELLOW}This includes all store configurations, price formulas,${NC}"
    echo -e "  ${YELLOW}field settings, and insertion history.${NC}"
    echo ""
    read -rp "  Remove database data? (y/N): " remove_data
    if [[ "$remove_data" == "y" || "$remove_data" == "Y" ]]; then
        print_step "Removing Docker volume (database data)..."
        docker volume rm "${COMPOSE_PROJECT}_pgdata" 2>/dev/null || \
        docker volume rm "product-entry_pgdata" 2>/dev/null || true
        print_ok "Database data removed"
    else
        print_ok "Database data preserved in Docker volume"
    fi

    # Remove application files
    print_step "Removing application files..."
    rm -rf "$INSTALL_DIR"
    print_ok "Application files removed"

    # Cleanup Docker
    print_step "Cleaning up Docker resources..."
    docker image prune -f >/dev/null 2>&1
    docker builder prune -f >/dev/null 2>&1
    print_ok "Docker cleanup complete"

    print_header "REMOVAL COMPLETE"
    echo ""
    echo -e "  ${GREEN}Product Entry has been removed.${NC}"
    if [[ "$remove_data" != "y" && "$remove_data" != "Y" ]]; then
        echo -e "  ${BOLD}Note:${NC} Database data preserved. Reinstall to reconnect."
    fi
    echo ""
}

do_remove_silent() {
    cd "$INSTALL_DIR" 2>/dev/null || true
    $DOCKER_COMPOSE -f docker-compose.prod.yml -p "$COMPOSE_PROJECT" down 2>/dev/null || \
    $DOCKER_COMPOSE -p "$COMPOSE_PROJECT" down 2>/dev/null || true
    rm -rf "$INSTALL_DIR"
}

# ════════════════════════════════════════════════════════
#  MAIN MENU
# ════════════════════════════════════════════════════════
main() {
    clear
    echo ""
    echo -e "${BLUE}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BLUE}║${NC}                                                           ${BLUE}║${NC}"
    echo -e "${BLUE}║${NC}   ${BOLD}Product Entry${NC} - Multi-Store Item Management            ${BLUE}║${NC}"
    echo -e "${BLUE}║${NC}                                                           ${BLUE}║${NC}"
    echo -e "${BLUE}╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""

    # Show current status
    if [ -d "$INSTALL_DIR" ]; then
        local status_color="${RED}"
        local status_text="Stopped"
        if curl -sf "http://localhost:${PORT}/api/health" >/dev/null 2>&1; then
            status_color="${GREEN}"
            status_text="Running"
        fi
        local current_ip=""
        if [ -f "${INSTALL_DIR}/.env" ]; then
            current_ip=$(grep '^SERVER_IP=' "${INSTALL_DIR}/.env" 2>/dev/null | cut -d'=' -f2)
        fi
        echo -e "  Status:  ${status_color}${BOLD}${status_text}${NC}"
        [ -n "$current_ip" ] && echo -e "  Address: ${CYAN}http://${current_ip}${NC}"
        echo -e "  Path:    ${INSTALL_DIR}"
    else
        echo -e "  Status:  ${YELLOW}Not installed${NC}"
    fi

    echo ""
    echo -e "  ${BOLD}1)${NC}  Install     ${GREEN}Fresh production install${NC}"
    echo -e "  ${BOLD}2)${NC}  Update      ${CYAN}Pull latest, preserve data, rebuild${NC}"
    echo -e "  ${BOLD}3)${NC}  Remove      ${RED}Stop and remove application${NC}"
    echo -e "  ${BOLD}4)${NC}  Exit"
    echo ""
    read -rp "  Select option [1-4]: " choice
    echo ""

    case "$choice" in
        1) do_install ;;
        2) do_update ;;
        3) do_remove ;;
        4) echo "  Bye!"; exit 0 ;;
        *) print_error "Invalid option."; exit 1 ;;
    esac
}

main
